# Generated by Django 4.0 on 2023-06-28 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_alter_customuser_groups_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='imagenes_calificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clasificacion', models.CharField(max_length=20)),
                ('image', models.ImageField(upload_to='visuales/images/')),
            ],
            options={
                'verbose_name_plural': 'imagenes de calificacion',
            },
        ),
        migrations.CreateModel(
            name='metasIP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_IP_excelente', models.IntegerField()),
                ('meta_IP_bueno', models.IntegerField()),
                ('meta_IP_regular', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Metas IP',
            },
        ),
        migrations.CreateModel(
            name='Mortalidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productor', models.CharField(max_length=1000)),
                ('ciclo', models.IntegerField()),
                ('sexo', models.CharField(max_length=1000)),
                ('semana', models.IntegerField()),
                ('total_semana', models.IntegerField(null=True)),
                ('total_acumulada', models.IntegerField(null=True)),
                ('acumulada_porcentaje', models.DecimalField(decimal_places=50, max_digits=1000, null=True)),
                ('saldo_aves', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.customuser')),
            ],
            options={
                'verbose_name_plural': 'mortalidades',
            },
        ),
        migrations.CreateModel(
            name='Cicloproduccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productor', models.CharField(max_length=1000)),
                ('ciclo', models.IntegerField()),
                ('dias_ciclo', models.IntegerField()),
                ('lote', models.CharField(max_length=1000)),
                ('raza', models.CharField(max_length=1000)),
                ('sexo', models.CharField(max_length=1000)),
                ('aves_iniciales', models.IntegerField()),
                ('aves_finales', models.IntegerField()),
                ('peso_inicial_gramos', models.DecimalField(decimal_places=5, max_digits=1000)),
                ('peso_final_gramos', models.DecimalField(decimal_places=5, max_digits=1000)),
                ('consumo_total_ave_kilogramos', models.DecimalField(decimal_places=5, max_digits=1000)),
                ('conversion_acumulada', models.DecimalField(decimal_places=5, max_digits=1000)),
                ('indice_productividad', models.DecimalField(decimal_places=5, max_digits=1000)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.customuser')),
            ],
            options={
                'verbose_name_plural': 'ciclos de produccion',
            },
        ),
        migrations.CreateModel(
            name='Alimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productor', models.CharField(max_length=1000)),
                ('ciclo', models.IntegerField()),
                ('sexo', models.CharField(max_length=1000)),
                ('semana', models.IntegerField()),
                ('consumo_ave', models.DecimalField(decimal_places=5, max_digits=1000)),
                ('peso_ave', models.DecimalField(decimal_places=5, max_digits=1000)),
                ('c_a_acum', models.DecimalField(decimal_places=5, max_digits=1000)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.customuser')),
            ],
            options={
                'verbose_name_plural': 'alimentos',
            },
        ),
    ]
