# Generated by Django 4.2.2 on 2023-06-24 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='bodega',
            field=models.CharField(choices=[('MO', 'Monterilla'), ('CR', 'Crucero'), ('PE', 'Pescador'), ('SN', 'San Nicolas')], default='MO', max_length=2),
        ),
    ]
